suberisedapps
nikgapps/config pull request #26
Opened 2021-04-07 06:06 UTC by gautam1512

2021-04-07 09:54 UTC, DrAmoled requested changes
Please remove the archive path, so it will be 11/gautam.config instead of archive/11/gautam.config

2021-04-08 00:51 UTC, gautam1512 commented
I have done that now, is it okay?

2021-04-08 01:30 UTC, nikhilmenghani commented
> I have done that now, is it okay?

You renamed sample.config to Gautam.config. Make sure you only change files in 11 or 10 folder. Better fork the repository and start again and send pull request.

2021-04-08 06:26 UTC, gautam1512 commented
Sir i have tried putting the ultimatum.config file in config/11 folder. I hope, i have done this right this time.

2021-04-08 20:07 UTC, nikgapps commented
@gautam1512 Your pull request has 3 changes, there should only be 1 change per android version. Please fork the repository, add your config to 10 or 11 folder and send the pull request.

2021-04-09 02:42 UTC, gautam1512 commented
Okay sir I try again.

On Fri, Apr 9, 2021, 1:37 AM Nikhil Menghani ***@***.***>
wrote:

> @gautam1512 <https://github.com/gautam1512> Your pull request has 3
> changes, there should only be 1 change per android version. Please fork the
> repository, add your config to 10 or 11 folder and send the pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nikgapps/config/pull/26#issuecomment-816136887>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATRJ3H3GVSOWGWQHL43Z7VTTHYEI3ANCNFSM42QDHYPA>
> .
>

2021-04-10 23:30 UTC, nikhilmenghani commented
@gautam1512 there should be no changes in archive folder. Kindly resend the pull request after making the changes. Only changes from 10 or 11 folder will be accepted

2021-04-11 06:32 UTC, DrAmoled requested changes
Adjustment needed according to the comments I put in your config

2021-04-11 06:32 UTC, DrAmoled commented on 11/subapps.config
> +>>SetupWizard=0
SetupWizard need to have value of 1 even if you are using Pixel Setup Wizard

2021-04-11 06:32 UTC, DrAmoled commented on 11/ultimatum.config
> +>>SetupWizard=0
Same as previous comment

2021-04-11 06:32 UTC, DrAmoled commented on 11/ultimatum.config
> +GoogleFiles=1
Why this appset is 1 when you put 0 in both sub appset

2021-04-12 06:30 UTC, nikhilmenghani commented
@gautam1512 can you make the changes today?

I'll close the pull request if there is no response. Send the pull request again if you need.

2021-04-13 02:18 UTC, closed without merging