Personal gapps
nikgapps/config pull request #5
Opened 2021-04-04 17:14 UTC by arunganesh97

2021-04-04 18:32 UTC, nikhilmenghani commented on 11/arun-&-gapps.config
> +Pixelize=1
When you set Pixelize=1 and set Packages=0 inside of Pixelize, it will not include any of the packages inside the app set, please set Pixelize-0 if you don't want PixelSetupWizard. if you want PixelSetupWizard, please set all the packages inside Pixelize=1.

2021-04-04 18:33 UTC, nikhilmenghani commented
Please make the changes as commented and send the pull request again.

2021-04-05 02:54 UTC, nikgapps requested changes
Also, please remove the '&' from the file name, some symbols will cause issues while building the gapps.

2021-04-05 03:17 UTC, nikhilmenghani requested changes

2021-04-05 03:17 UTC, nikhilmenghani commented on 11/arun97-gapps.config
> +GoogleWallpaper=2
Do you indent to keep GoogleWallpaper=2? only the packages with value=1 will be included. Rest will be ignored. Let me know if you want me to proceed ahead. If not, make changes and send pull request again.

2021-04-05 04:19 UTC, arunganesh97 commented on 11/arun97-gapps.config
> +GoogleWallpaper=2
Proceed it brother! I'll correct those issues in future requests...

2021-04-05 04:51 UTC, merged